CREATE TABLE IF NOT EXISTS PLANB_MESSAGE(
  BROKER_ID VARCHAR(255) NOT NULL,
  MESSAGE_ID VARCHAR(36) NOT NULL,
  MESSAGE_STATUS VARCHAR(255) NOT NULL,
  ENCODED_DATA BLOB NOT NULL,
  CTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(BROKER_ID, MESSAGE_ID)
);
